### ISSUE TITLE
Consider git-flow branching

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet-admin#10]
We can consider having a `development` branch to check things into and not interfere with the CI/CD Pipeline.

What do you think @pcast01?

**Comment by pcast01** [comment]
Sounds good.

**Comment by fpigeonjr** [comment]
This will probably resolve some of the merge conflicts we are having.

**Comment by fpigeonjr** [comment]
also @pcast01  do you want to make the `dev` the default branch?

**Comment by pcast01** [comment]
Yes. I will do that now.
