### ISSUE TITLE
Allow calendar events to go past 2020

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet-admin#21]
> calendar for events only goes through 2020 – there are no years beyond 2020?

<img width="1444" alt="Screen Shot 2020-07-11 at 7 21 47 PM" src="https://user-images.githubusercontent.com/4629398/87236211-c929b880-c3ab-11ea-90fa-bb7e9d55620e.png">

**Comment by pcast01** [comment]
Added 2 more years.
