### ISSUE TITLE
Cannot delete old blog posts

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet-admin#22]
> OK, the admin portal does appear to be saving the blog data as I have now created multiple copies – however, the additional copies cannot be deleted. 

 > When I refresh the window to clear old data an error screen appears that can only be cleared by closing the window completely and logging back in.

**Comment by pcast01** [comment]
We do not have a way to delete the blog posts yet but I do see that there are 5 blog posts they created.

**Comment by pcast01** [comment]
We have to talk about this.

**Comment by pcast01** [comment]
Added ability to delete blogs. There is no notification on the client side though.

**Comment by pcast01** [comment]
I have added a way to delete blogs but there is no message or anything that the user has deleted a blog yet.

**Comment by pcast01** [comment]
I added the notifications and also asking the user if they want to delete the blog first.
