### ISSUE TITLE
Jobs are not matching up

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet-admin#23]
Two jobs in the admin area and only one showing on the frontend.

<img width="1716" alt="Screen Shot 2020-07-11 at 7 28 18 PM" src="https://user-images.githubusercontent.com/4629398/87236281-d1362800-c3ac-11ea-8da5-d936872851c1.png">

**Comment by pcast01** [comment]
Frank, I checked the job end date  and it was the same day, 7-8-2020 and that should be chosen as another day in the future to keep it on showing. I changed the end date to (8-8-2020) and now it shows up. So either they put the same day in there or they put another date and it didn't save. We might want to check what date is input.
