### ISSUE TITLE
Get 2 new partner logos from their respective websites.

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet-admin#27]
Trimedx: https://trimedx.com/

Agiliti:   https://www.agilitihealth.com/

**Comment by fpigeonjr** [comment]
@pcast01,  I was able to get them from their websites.
![agiliti-logo](https://user-images.githubusercontent.com/4629398/88418019-89e66900-cda8-11ea-94a9-53eb5d9b8e3e.png)
![trimedx-logo](https://user-images.githubusercontent.com/4629398/88418021-8a7eff80-cda8-11ea-9a3c-eb04b5dfb326.png)

**Comment by pcast01** [comment]
@fpigeonjr can you make the trimedx image with a black background?

**Comment by fpigeonjr** [comment]
yes of course

**Comment by fpigeonjr** [comment]
Try this one @pcast01 
![trimedx-logo-black](https://user-images.githubusercontent.com/4629398/88435674-4c91d380-cdc8-11ea-917a-bbec6cd14e68.png)

**Comment by pcast01** [comment]
Thanks! That will work.
